### ISSUE TITLE
Volume numbers assigned to VC and VP

### ISSUE THREAD

**Issue by SylvieRetout** [UUPharmacometrics/assemblerr#9]
assemblerr Version: 0.0.0.9003. I tested a 2-compartment model with first order absorption. The volume numbers assigned to Vc and Vp are not the correct ones - I should get V2 and V3 and I have V1 and V2. See my example below:

> pkm <- pk_model() +
+   pk_absorption_fo() +
+   algebraic(S2~1/1000) +
+   pk_absorption_fo_lag() +
+   pk_distribution_2cmp() +
+   pk_elimination_linear() +
+   obs_combined(conc~C["central"]*S2) 
> 
> render(pkm)
$PROBLEM
$INPUT ID TIME DV AMT
$DATA data.csv IGNORE=@
$SUBROUTINES ADVAN4  TRANS4 
$MODEL COMP=(DEPOT) COMP=(CENTRAL) COMP=(PERIPHERAL)
$PK
MAT = THETA(1) * EXP(ETA(1))
MDT = THETA(2) * EXP(ETA(2))
VC = THETA(3) * EXP(ETA(3))
VP = THETA(4) * EXP(ETA(4))
Q = THETA(5) * EXP(ETA(5))
CL = THETA(6) * EXP(ETA(6))
ALAG1 = MDT
KA = 1/MAT
S2 = 1/1000
V1 = VC
V2 = VP
$ERROR
CONC = A(2)/VC * S2
Y = CONC + EPS(1) + CONC * EPS(2)

**Comment by sebastianueckert** [comment]
I believe it is the same problem as #2 and should be fixed now.

Could you please check again with the latest version?

(Please note that the building block pk_absorption_fo_lag() is both first-order absorption and lag time)

**Comment by SylvieRetout** [comment]
Hi Sebastian,

I have checked - but unfortunately I have still the same following lines: V1=VC and V2=VP.
I am using assemblerr version 0.0.0.9003.

(Thanks for the note regarding pk_absorption_fo_lag())

**Comment by SylvieRetout** [comment]
Hi Sebastian,

Although I was using the most updated versions of assemblerr (9003 and later on 9004), I managed to get the right numbers for those volumes only once I closed Rstudio and open it again. It was not possible without closing Rstudio.

Kind regards,

Sylvie

**Comment by sebastianueckert** [comment]
Great. Thanks for letting me know!
